name: Build
on: pull_request
jobs:
  build:
    name: Commit Stage Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
